### Registration
POST http://172.16.254.134:8080/auth/registration
Content-Type: application/json

{
  "name": "Avazbek",
  "surname": "Yuldashev",
  "username": "telegram.vzlom@gmail.com",
  "password": "12345"
}

### Login
POST http://172.16.254.134:8080/auth/login
Content-Type: application/json

{
  "username": "telegram.vzlom@gmail.com",
  "password": "12345"
}

### resend email
GET http://localhost:8080/auth/registration/email-verification-resend
Content-Type: application/json

{
  "phone": "avaz.yuldashev2004@gmail.com"
}

### Reset Password
POST http://localhost:8080/auth/reset-password
Content-Type: application/json

{
  "username": "998902597891"
}

### Reset Password
POST http://localhost:8080/auth/reset-password
Content-Type: application/json

{
  "username": "telegram.vzlom@gmail.com"
}

### Confirm Reset Password
POST http://localhost:8080/auth/reset-password-confrim
Content-Type: application/json

{
  "username": "telegram.vzlom@gmail.com",
  "password": "11223344",
  "confirmCode": "79313"
}



###
GET http://172.16.254.134:8080/auth/registration/email-verification/eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyMzhiMmI4ZS1jYTllLTQyNzItYjMzNC0yMGJlYzA3NmQ0MTMiLCJpYXQiOjE3NTcwNjE2NTcsImV4cCI6MTc1NzA2NTI1N30.yM2f-oekXvpplCUVLv39Zi_RBARicWSQ0VkS2hGZZAWfnCFEExbE_F8NeveUxH4PyNFReOtxaF36tapNwZa1QQ/UZ